version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  groups:
    types:
      patterns:
        - "@types/*"
    eslint:
      patterns:
        - "typescript-eslint"
        - "eslint*"
        - "@eslint/*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
