categories:
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🔧 Internal Changes'
    label: 'refactor'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📖 Documentation'
    label: 'documentation'
exclude-labels:
  - "dependencies"
template: |
  $CHANGES
