name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Node
      uses: actions/setup-node@v2.2.0
      with:
        node-version: 'lts/*'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: Lint
      run: yarn run lint --no-fix --max-warnings 0 --format stylish
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Node
      uses: actions/setup-node@v2.2.0
      with:
        node-version: 'lts/*'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: build
      run: yarn build
