name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Node
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 'lts/*'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: Lint
      run: yarn run lint --no-fix --max-warnings 0 --format stylish
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Node
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 'lts/*'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: build
      run: yarn build
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Node
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 'lts/*'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: test
      run: yarn test
    - uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # required
        files: cobertura-coverage.xml
